@startuml

title Diagrama de Classes - com Herança, Classe Abstrata e Interface

package ifpr.paranavai.jogo.modelo <<Frame>> {
    interface IFase
    class FaseUm
    class Personagem
    class Inimigo
    class Tiro
    class ElementoGrafico
    note right of ElementoGrafico::carregar
        Itálico indica que
        o método é abstrato
    end note
}

package java.awt.event <<Frame>> {
    interface ActionListener
    interface KeyListener
}


package javax.swing <<Frame>> {
  class JPanel
}

abstract class ElementoGrafico <<abstract>> {
    -int posicaoEmX
    -int posicaoEmY
    -Image imagem
    -int larguraImagem
    -int alturaImagem    
    +{abstract} void carregar()
    +{abstract} void atualizar()
    .. getters e setters ..
}

class FaseUm {
    -Image fundo
    -Timer timer
    +FaseUm()
    +void paint(Graphics g)
    +void keyTyped(KeyEvent e)
    +void keyPressed(KeyEvent e)
    +void keyReleased(KeyEvent e)
    +void actionPerformed(ActionEvent e)
}

class Personagem{
    -int deslocamentoEmX
    -int deslocamentoEmY
    +Personagem()
    +void atirar()
    +void mover(KeyEvent tecla)
    +void parar(KeyEvent tecla)
    .. getters e setters ..
}

class Inimigo{
    +Inimigo(int xAleatorio, int yAleatorio)
}

class Tiro {
    +Tiro(int posicaoPersonagemEmX, int posicaoPersonagemEmY)
}

interface IFase {    
    +void inicializaInimigos()
}

class JPanel
interface ActionListener <<interface>>
interface KeyListener <<interface>>

FaseUm -up-|> JPanel: extends
FaseUm -up.|> ActionListener: implements
FaseUm -up.|> KeyListener: implements
FaseUm -right.|> IFase: implements

FaseUm "1" *-right-> "1" Personagem
Inimigo "*" <-right- "1" FaseUm

Personagem "1" *--> "*" Tiro
Personagem --|> ElementoGrafico: extends

Tiro --|> ElementoGrafico: extends

Inimigo --|> ElementoGrafico: extends
@enduml