@startuml

title Diagrama de Classes - Sem Herança

package ifpr.paranavai.jogo.modelo <<Frame>> {
  class Fase
  class Personagem
  class Inimigo
  class Tiro
}

package java.awt.event <<Frame>> {
  interface ActionListener
  interface KeyListener

}


package javax.swing <<Frame>> {
  class JPanel
}

class Fase {
    -Image fundo
    -Timer timer
    +Fase()
    +void inicializaInimigos()
    +void paint(Graphics g)
    +void keyTyped(KeyEvent e)
    +void keyPressed(KeyEvent e)
    +void keyReleased(KeyEvent e)
    +void actionPerformed(ActionEvent e)
}

class Personagem{
    -int deslocamentoEmX
    -int deslocamentoEmY
    -int posicaoEmX
    -int posicaoEmY
    -Image imagem
    -int larguraImagem
    -int alturaImagem
    +Personagem()
    +void carregar()
    +void atualizar()
    +void atirar()
    +void mover(KeyEvent tecla)
    +void parar(KeyEvent tecla)
    .. getters e setters ..
}

class Inimigo{
    -int posicaoEmX
    -int posicaoEmY
    -Image imagem
    -int larguraImagem
    -int alturaImagem
    +Inimigo(int xAleatorio, int yAleatorio)
    +void carregar()
    +void atualizar()
    .. getters e setters ..
}

class Tiro{
    -int posicaoEmX
    -int posicaoEmY
    -Image imagem
    -int larguraImagem
    -int alturaImagem
    +Tiro(int posicaoPersonagemEmX, int posicaoPersonagemEmY)
    +void carregar()
    +void atualizar()
    .. getters e setters ..
}

class JPanel
interface ActionListener <<interface>>
interface KeyListener <<interface>>

Fase -up-|> JPanel: extends
Fase -up.|> ActionListener: implements
Fase -up.|> KeyListener: implements

Fase "1" *--left--> "1" Personagem
Fase "1" *-right-> "*" Inimigo

Personagem "1" *--> "*" Tiro

@enduml